import {
  FamilyMember,
  Family,
  Task,
  HealthRecord,
  Medication,
  Appointment,
  ActivityEvent,
} from "@/types";

export const initialFamily: Family = {
  id: "fam-rao",
  name: "The Rao Family",
  primaryCity: "Hyderabad",
  memberIds: ["mem-anita", "mem-ramesh", "mem-arjun", "mem-meera"],
  primaryCoordinatorId: "mem-arjun",
  isCoordinatorAvailable: true,
  monthlySpendingLimit: 1500,
  createdAt: "2026-01-15T00:00:00Z",
};

export const initialFamilyMembers: FamilyMember[] = [
  {
    id: "mem-anita",
    name: "Anita Rao",
    relationship: "Mother",
    age: 68,
    location: "Jubilee Hills, Hyderabad",
    role: "DEPENDENT",
    healthStatusSummary: "Hypothyroidism & Mild Hypertension managed with daily therapy. Refill pending.",
    bloodGroup: "O+",
    allergies: ["Penicillin", "Sulfa drugs"],
    conditions: ["Primary Hypothyroidism", "Essential Hypertension"],
    avatarColor: "bg-rose-100 text-rose-800 border-rose-300",
    preferredLanguage: "te-IN",
    emergencyContact: {
      name: "Ramesh Rao (Spouse)",
      phone: "+91 98490 12345",
      relation: "Spouse",
      preferredHospital: "Apollo Hospitals, Jubilee Hills, Hyderabad",
    },
    permissions: {
      canViewRecords: true,
      canApprovePayments: true,
      canManageMedications: false,
      canCoordinateAppointments: false,
      categories: ["VIEW_RECORDS", "APPROVE_PAYMENTS", "EMERGENCY_ACCESS"],
    },
    insuranceId: "STAR-HLTH-9948271",
    primaryPhysician: "Dr. Sumathi Reddy (Endocrinology)",
  },
  {
    id: "mem-ramesh",
    name: "Ramesh Rao",
    relationship: "Father",
    age: 72,
    location: "Jubilee Hills, Hyderabad",
    role: "DEPENDENT",
    healthStatusSummary: "Post-PTCA cardiac recovery (6 months). Routine cardiology follow-up in 5 days.",
    bloodGroup: "B+",
    allergies: ["No known allergies"],
    conditions: ["Coronary Artery Disease (Post-Stent)", "Type 2 Diabetes Mellitus"],
    avatarColor: "bg-blue-100 text-blue-800 border-blue-300",
    preferredLanguage: "te-IN",
    emergencyContact: {
      name: "Arjun Rao (Son)",
      phone: "+91 93811 88069",
      relation: "Son",
      preferredHospital: "Apollo Hospitals, Jubilee Hills, Hyderabad",
    },
    permissions: {
      canViewRecords: true,
      canApprovePayments: true,
      canManageMedications: false,
      canCoordinateAppointments: false,
      categories: ["VIEW_RECORDS", "APPROVE_PAYMENTS", "EMERGENCY_ACCESS"],
    },
    insuranceId: "STAR-HLTH-9948272",
    primaryPhysician: "Dr. K. S. Rao (Chief Interventional Cardiologist)",
  },
  {
    id: "mem-arjun",
    name: "Arjun Rao",
    relationship: "Son",
    age: 38,
    location: "Indiranagar, Bengaluru",
    role: "CARE_COORDINATOR",
    healthStatusSummary: "Primary Health Manager for parents. Coordinates refills, hospital approvals, and logistics.",
    bloodGroup: "O+",
    allergies: ["Dust mites"],
    conditions: [],
    avatarColor: "bg-slate-900 text-white border-slate-900",
    preferredLanguage: "en-IN",
    emergencyContact: {
      name: "Meera Rao (Sister)",
      phone: "+91 94440 55667",
      relation: "Sister",
      preferredHospital: "Manipal Hospital, HAL Old Airport Rd, Bengaluru",
    },
    permissions: {
      canViewRecords: true,
      canApprovePayments: true,
      canManageMedications: true,
      canCoordinateAppointments: true,
      categories: [
        "VIEW_RECORDS",
        "UPLOAD_RECORDS",
        "MANAGE_MEDICATIONS",
        "MANAGE_APPOINTMENTS",
        "APPROVE_PAYMENTS",
        "AUTHORIZE_AGENT_ACTIONS",
        "EMERGENCY_ACCESS",
      ],
    },
    primaryPhysician: "Dr. Pradeep Kumar (Internal Medicine)",
  },
  {
    id: "mem-meera",
    name: "Meera Rao",
    relationship: "Daughter",
    age: 34,
    location: "Adyar, Chennai",
    role: "MEMBER",
    healthStatusSummary: "Secondary coordinator. Co-manages home diagnostics, diagnostic scheduling, and records.",
    bloodGroup: "B+",
    allergies: ["None"],
    conditions: [],
    avatarColor: "bg-teal-100 text-teal-800 border-teal-300",
    preferredLanguage: "en-IN",
    emergencyContact: {
      name: "Arjun Rao (Brother)",
      phone: "+91 98801 88990",
      relation: "Brother",
      preferredHospital: "Apollo Spectra, Alwarpet, Chennai",
    },
    permissions: {
      canViewRecords: true,
      canApprovePayments: true,
      canManageMedications: true,
      canCoordinateAppointments: true,
      categories: [
        "VIEW_RECORDS",
        "UPLOAD_RECORDS",
        "MANAGE_MEDICATIONS",
        "MANAGE_APPOINTMENTS",
        "APPROVE_PAYMENTS",
        "AUTHORIZE_AGENT_ACTIONS",
        "EMERGENCY_ACCESS",
      ],
    },
    primaryPhysician: "Dr. Ananya Sen (General Physician)",
  },
];

export const initialMedications: Medication[] = [
  {
    id: "med-thyronorm",
    name: "Thyronorm (Levothyroxine Sodium)",
    dosage: "50 mcg",
    frequency: "Once daily (Morning, 30 min before tea/breakfast)",
    patientId: "mem-anita",
    prescribingDoctor: "Dr. Sumathi Reddy",
    startDate: "2024-01-10",
    refillIntervalDays: 60,
    nextRefillDate: "2026-09-26",
    status: "ACTIVE",
    remainingDays: 3,
    currentStockUnits: 3,
    instructions: "Strictly empty stomach with plain water. Do not skip.",
    pharmacyName: "Apollo Pharmacy (Jubilee Hills Branch)",
    costEstimate: 485,
    prescriptionStatus: "VERIFIED",
    responsibleCoordinatorId: "mem-arjun",
    lastRefillDate: "2026-07-28",
  },
  {
    id: "med-telmisartan",
    name: "Telma (Telmisartan)",
    dosage: "40 mg",
    frequency: "Once daily (Post breakfast)",
    patientId: "mem-anita",
    prescribingDoctor: "Dr. K. S. Rao",
    startDate: "2024-02-15",
    refillIntervalDays: 30,
    nextRefillDate: "2026-10-10",
    status: "ACTIVE",
    remainingDays: 17,
    currentStockUnits: 17,
    instructions: "For BP regulation. Monitor weekly resting BP.",
    pharmacyName: "Apollo Pharmacy (Jubilee Hills Branch)",
    costEstimate: 320,
    prescriptionStatus: "VERIFIED",
    responsibleCoordinatorId: "mem-arjun",
    lastRefillDate: "2026-09-10",
  },
  {
    id: "med-metformin",
    name: "Glycomet-SR (Metformin)",
    dosage: "500 mg",
    frequency: "Twice daily (After breakfast & dinner)",
    patientId: "mem-ramesh",
    prescribingDoctor: "Dr. K. S. Rao",
    startDate: "2023-08-01",
    refillIntervalDays: 30,
    nextRefillDate: "2026-10-04",
    status: "ACTIVE",
    remainingDays: 11,
    currentStockUnits: 22,
    instructions: "Sustained release. Swallow whole with water.",
    pharmacyName: "MedPlus Jubilee Hills",
    costEstimate: 290,
    prescriptionStatus: "VERIFIED",
    responsibleCoordinatorId: "mem-arjun",
    lastRefillDate: "2026-09-04",
  },
  {
    id: "med-atorvastatin",
    name: "Atorva (Atorvastatin)",
    dosage: "20 mg",
    frequency: "Once daily (At bedtime)",
    patientId: "mem-ramesh",
    prescribingDoctor: "Dr. K. S. Rao",
    startDate: "2024-03-20",
    refillIntervalDays: 30,
    nextRefillDate: "2026-10-18",
    status: "ACTIVE",
    remainingDays: 25,
    currentStockUnits: 25,
    instructions: "Lipid lowering post-stent therapy.",
    pharmacyName: "Apollo Pharmacy (Jubilee Hills Branch)",
    costEstimate: 410,
    prescriptionStatus: "VERIFIED",
    responsibleCoordinatorId: "mem-arjun",
    lastRefillDate: "2026-09-18",
  },
];

export const initialTasks: Task[] = [
  {
    id: "task-refill-thyronorm",
    title: "Order Anita's Thyronorm 50mcg refill",
    description: "Stock down to 3 tablets (3 days remaining). Refill via Apollo Pharmacy + Delhivery cold chain.",
    familyMemberId: "mem-anita",
    ownerId: "mem-arjun",
    createdBy: "CareLoop Agent",
    priority: "URGENT",
    dueDate: "2026-09-25",
    status: "NEEDS_ATTENTION",
    source: "REFILL_TRIGGER",
    requiresApproval: true,
    requiredApprovalFromId: "mem-anita",
    approvalStatus: "PENDING",
    relatedMedicationId: "med-thyronorm",
    activityHistory: [
      {
        id: "act-t1",
        timestamp: "2026-09-23T06:30:00Z",
        actorName: "CareLoop Agent",
        actorType: "CARE_AGENT",
        action: "Identified refill threshold (<= 3 days remaining). Created actionable refill task.",
      },
    ],
    tags: ["Medication", "Refill", "Anita"],
  },
  {
    id: "task-prep-cardiology",
    title: "Prepare Ramesh's cardiology packet for Dr. K.S. Rao",
    description: "Collate recent Lipid profile, ECG scan, and 30-day blood pressure log ahead of Monday appointment.",
    familyMemberId: "mem-ramesh",
    ownerId: "mem-arjun",
    createdBy: "Arjun Rao",
    priority: "HIGH",
    dueDate: "2026-09-27",
    status: "IN_PROGRESS",
    source: "DOCTOR_FOLLOWUP",
    relatedAppointmentId: "apt-ramesh-cardio",
    relatedRecordId: "rec-lipid-ramesh",
    activityHistory: [
      {
        id: "act-t2",
        timestamp: "2026-09-22T14:10:00Z",
        actorName: "Arjun Rao",
        actorType: "USER",
        action: "Linked recent Apollo lab report to appointment dossier.",
      },
    ],
    tags: ["Appointment Prep", "Cardiology", "Ramesh"],
  },
  {
    id: "task-home-ecg-approval",
    title: "Approve Home 12-Lead ECG diagnostic visit",
    description: "Meera requested Apollo Homecare mobile ECG technician visit to Hyderabad home before follow-up.",
    familyMemberId: "mem-ramesh",
    ownerId: "mem-meera",
    createdBy: "Meera Rao",
    priority: "NORMAL",
    dueDate: "2026-09-25",
    status: "WAITING_FOR_APPROVAL",
    source: "USER",
    requiresApproval: true,
    requiredApprovalFromId: "mem-arjun",
    approvalStatus: "PENDING",
    relatedAppointmentId: "apt-ramesh-cardio",
    activityHistory: [
      {
        id: "act-t3",
        timestamp: "2026-09-22T18:45:00Z",
        actorName: "Meera Rao",
        actorType: "USER",
        action: "Requested payment & appointment slot approval (₹1,200 Apollo Homecare).",
      },
    ],
    tags: ["Diagnostics", "Approval", "Ramesh"],
  },
  {
    id: "task-ophthalmology-check",
    title: "Schedule Anita's annual diabetic/hypertensive eye check",
    description: "Annual fundus and retina evaluation recommended at L.V. Prasad Eye Institute.",
    familyMemberId: "mem-anita",
    ownerId: "mem-meera",
    createdBy: "Meera Rao",
    priority: "LOW",
    dueDate: "2026-10-15",
    status: "NEEDS_ATTENTION",
    source: "USER",
    activityHistory: [
      {
        id: "act-t4",
        timestamp: "2026-09-20T10:00:00Z",
        actorName: "Meera Rao",
        actorType: "USER",
        action: "Noted recommendation from Dr. Sumathi Reddy visit.",
      },
    ],
    tags: ["Eye Check", "Preventive", "Anita"],
  },
  {
    id: "task-past-atorva-delivery",
    title: "Ramesh's Atorvastatin 30-day refill delivered",
    description: "Delivered safely via Delhivery Express courier. AWB #DL928374619.",
    familyMemberId: "mem-ramesh",
    ownerId: "mem-arjun",
    createdBy: "CareLoop Agent",
    priority: "NORMAL",
    dueDate: "2026-09-18",
    status: "COMPLETED",
    source: "REFILL_TRIGGER",
    relatedMedicationId: "med-atorvastatin",
    externalRailRef: {
      type: "DELHIVERY",
      referenceId: "AWB-DL928374619",
      status: "DELIVERED",
      lastUpdated: "2026-09-18T16:20:00Z",
    },
    activityHistory: [
      {
        id: "act-t5",
        timestamp: "2026-09-18T16:20:00Z",
        actorName: "Delhivery Courier",
        actorType: "PROVIDER",
        action: "Package handed over to security at Jubilee Hills residence.",
      },
    ],
    tags: ["Completed", "Logistics", "Ramesh"],
  },
];

export const initialHealthRecords: HealthRecord[] = [
  {
    id: "rec-lipid-ramesh",
    title: "Comprehensive Lipid Profile & HbA1c Report",
    documentType: "LAB_REPORT",
    patientId: "mem-ramesh",
    date: "2026-09-11",
    doctor: "Dr. K. S. Rao",
    hospital: "Apollo Diagnostics, Jubilee Hills",
    tags: ["Lipid Profile", "Diabetes", "Cardiology"],
    fileSize: "1.4 MB (PDF)",
    uploadSource: "HOSPITAL_PORTAL",
    pipelineStatus: "VERIFIED",
    extractedMetadata: {
      reviewStatus: "VERIFIED_BY_HUMAN",
      confidenceScore: 0.96,
      inferredNotes: "Extracted via CareLoop OCR from Apollo lab sheet. Inferred key metrics require clinician contextualization.",
      diagnosisSummary: "Controlled dyslipidemia under statin therapy; HbA1c shows fair glycemic control.",
      doctorName: "Dr. K. S. Rao",
      hospitalName: "Apollo Diagnostics, Jubilee Hills",
      documentDate: "2026-09-11",
      followUpDate: "2026-09-28",
      keyMetrics: [
        { label: "HbA1c (Glycosylated Hemoglobin)", value: "7.1", unit: "%", status: "BORDERLINE", referenceRange: "< 6.5%" },
        { label: "Fasting Blood Glucose", value: "128", unit: "mg/dL", status: "BORDERLINE", referenceRange: "70-100 mg/dL" },
        { label: "Total Cholesterol", value: "182", unit: "mg/dL", status: "NORMAL", referenceRange: "< 200 mg/dL" },
        { label: "Triglycerides", value: "158", unit: "mg/dL", status: "BORDERLINE", referenceRange: "< 150 mg/dL" },
        { label: "HDL Cholesterol", value: "44", unit: "mg/dL", status: "NORMAL", referenceRange: "> 40 mg/dL" },
        { label: "LDL Cholesterol", value: "106", unit: "mg/dL", status: "NORMAL", referenceRange: "< 100 mg/dL" },
      ],
      prescribedMedicines: ["Continue Atorva 20mg", "Continue Glycomet-SR 500mg"],
    },
  },
  {
    id: "rec-discharge-ramesh",
    title: "Post-Angioplasty (PTCA) Discharge Summary",
    documentType: "DISCHARGE_SUMMARY",
    patientId: "mem-ramesh",
    date: "2026-03-22",
    doctor: "Dr. K. S. Rao",
    hospital: "Apollo Hospitals, Jubilee Hills, Hyderabad",
    tags: ["Cardiology", "Stent", "Discharge"],
    fileSize: "3.2 MB (PDF)",
    uploadSource: "MANUAL_UPLOAD",
    pipelineStatus: "VERIFIED",
    extractedMetadata: {
      reviewStatus: "VERIFIED_BY_HUMAN",
      confidenceScore: 0.98,
      inferredNotes: "Hospital formal discharge record. Successful drug-eluting stent (DES) placement to LAD.",
      diagnosisSummary: "Single vessel CAD (LAD 85% stenosis). Successful DES stent implant. Stable vitals on discharge.",
      doctorName: "Dr. K. S. Rao",
      hospitalName: "Apollo Hospitals, Jubilee Hills",
      documentDate: "2026-03-22",
      keyMetrics: [
        { label: "LVEF (Ejection Fraction)", value: "55", unit: "%", status: "NORMAL", referenceRange: "50-70%" },
        { label: "Post-op Blood Pressure", value: "124/82", unit: "mmHg", status: "NORMAL", referenceRange: "120/80" },
      ],
      prescribedMedicines: ["Dual antiplatelet therapy", "Atorvastatin 20mg", "Metformin 500mg"],
    },
  },
  {
    id: "rec-thyroid-anita",
    title: "Thyroid Profile (Free T3, Free T4, Ultrasensitive TSH)",
    documentType: "LAB_REPORT",
    patientId: "mem-anita",
    date: "2026-08-15",
    doctor: "Dr. Sumathi Reddy",
    hospital: "Vijaya Diagnostic Centre, Hyderabad",
    tags: ["Endocrinology", "Thyroid", "Anita"],
    fileSize: "850 KB (PDF)",
    uploadSource: "WHATSAPP_SYNC",
    pipelineStatus: "VERIFIED",
    extractedMetadata: {
      reviewStatus: "VERIFIED_BY_HUMAN",
      confidenceScore: 0.94,
      inferredNotes: "TSH remains within therapeutic target on 50mcg dosage.",
      diagnosisSummary: "Euthyroid state maintained under Thyronorm 50mcg replacement therapy.",
      doctorName: "Dr. Sumathi Reddy",
      hospitalName: "Vijaya Diagnostic Centre",
      documentDate: "2026-08-15",
      keyMetrics: [
        { label: "Ultrasensitive TSH", value: "3.84", unit: "uIU/mL", status: "NORMAL", referenceRange: "0.45 - 4.50 uIU/mL" },
        { label: "Free T4", value: "1.22", unit: "ng/dL", status: "NORMAL", referenceRange: "0.82 - 1.77 ng/dL" },
        { label: "Free T3", value: "2.9", unit: "pg/mL", status: "NORMAL", referenceRange: "2.0 - 4.4 pg/mL" },
      ],
      prescribedMedicines: ["Maintain Thyronorm 50 mcg"],
    },
  },
  {
    id: "rec-rx-anita",
    title: "Endocrinology Outpatient Prescription & Diet Chart",
    documentType: "PRESCRIPTION",
    patientId: "mem-anita",
    date: "2026-07-25",
    doctor: "Dr. Sumathi Reddy",
    hospital: "Apollo Hospitals, Hyderabad",
    tags: ["Prescription", "Thyroid", "Anita"],
    fileSize: "1.1 MB (Image)",
    uploadSource: "MANUAL_UPLOAD",
    pipelineStatus: "NEEDS_VERIFICATION",
    extractedMetadata: {
      reviewStatus: "REVIEW_PENDING",
      confidenceScore: 0.91,
      inferredNotes: "Handwritten prescription scanned. OCR detected 2 medications with high confidence. Human review requested.",
      diagnosisSummary: "Hypothyroidism stable; advice to re-check TSH every 6 months.",
      doctorName: "Dr. Sumathi Reddy",
      hospitalName: "Apollo Hospitals, Hyderabad",
      documentDate: "2026-07-25",
      prescribedMedicines: ["Thyronorm 50mcg (60 days)", "Telma 40mg (30 days)"],
    },
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: "apt-ramesh-cardio",
    patientId: "mem-ramesh",
    doctor: "Dr. K. S. Rao",
    speciality: "Chief Interventional Cardiologist",
    hospital: "Apollo Hospitals, Jubilee Hills, Hyderabad",
    date: "2026-09-28",
    time: "10:30 AM",
    location: "OPD Block A, Room 204",
    status: "UPCOMING",
    purpose: "6-month post-angioplasty cardiac follow-up and lipid panel review",
    notes: "6-month post-angioplasty follow-up. Review ECG and latest lipid profile.",
    relatedRecordIds: ["rec-lipid-ramesh", "rec-discharge-ramesh"],
    preparationNotes: [
      "Carry previous discharge summary printout (linked).",
      "Ensure overnight fasting not required for routine OPD, but have latest BP log ready.",
      "Arjun to accompany virtually via speakerphone during doctor's consultation.",
    ],
    suggestedQuestions: [
      "Has the lipid profile improved adequately under Atorvastatin 20mg?",
      "Is an exercise treadmill test (TMT) required before resuming morning walks?",
      "Can Glycomet-SR dosage be maintained given the current HbA1c of 7.1%?",
    ],
  },
  {
    id: "apt-anita-endocrine",
    patientId: "mem-anita",
    doctor: "Dr. Sumathi Reddy",
    speciality: "Consultant Endocrinologist",
    hospital: "Apollo Hospitals, Jubilee Hills, Hyderabad",
    date: "2026-10-07",
    time: "04:15 PM",
    location: "Consultation Suites, 3rd Floor",
    status: "UPCOMING",
    purpose: "Bi-annual thyroid function evaluation and dosage compliance check",
    notes: "Bi-annual thyroid review and medication titration check.",
    relatedRecordIds: ["rec-thyroid-anita", "rec-rx-anita"],
    preparationNotes: [
      "Verify latest fasting TSH test is uploaded at least 48 hours prior.",
      "Review morning medication timing compliance.",
    ],
    suggestedQuestions: [
      "TSH is currently 3.84 uIU/mL. Should we continue Thyronorm 50mcg or adjust?",
      "Are any dietary calcium supplements interfering with morning thyroid absorption?",
      "When is the next antibody or ultrasound scan recommended?",
    ],
  },
];

export const initialActivityEvents: ActivityEvent[] = [
  {
    id: "act-01",
    timestamp: "2026-09-23T06:30:15Z",
    actor: { id: "care-agent", name: "CareLoop Agent", type: "CARE_AGENT" },
    actionType: "TASK_CREATED",
    entityType: "TASK",
    entityId: "task-refill-thyronorm",
    description: "Identified Thyronorm 50mcg stock threshold (3 days remaining). Auto-generated urgent refill task.",
    whyExplanation:
      "CareLoop requested a refill because Anita's verified prescription indicates daily morning use and recorded stock is below the configured 5-day safety threshold.",
  },
  {
    id: "act-02",
    timestamp: "2026-09-22T18:45:00Z",
    actor: { id: "mem-meera", name: "Meera Rao", type: "USER" },
    actionType: "APPROVAL_REQUESTED",
    entityType: "TASK",
    entityId: "task-home-ecg-approval",
    description: "Requested approval from Arjun Rao for ₹1,200 Apollo Homecare ECG visit for Father.",
    whyExplanation:
      "Pre-appointment diagnostic check requested by Dr. K.S. Rao before Ramesh's upcoming cardiology consultation.",
  },
  {
    id: "act-03",
    timestamp: "2026-09-22T14:10:00Z",
    actor: { id: "mem-arjun", name: "Arjun Rao", type: "USER" },
    actionType: "TASK_STATUS_CHANGED",
    entityType: "TASK",
    entityId: "task-prep-cardiology",
    description: "Updated Ramesh's cardiology prep task to IN_PROGRESS and attached recent lipid panel.",
    whyExplanation:
      "Arjun verified that previous lab metrics were verified and attached them to the pre-visit dossier.",
  },
  {
    id: "act-04",
    timestamp: "2026-09-18T16:20:00Z",
    actor: { id: "prov-delhivery", name: "Delhivery Logistics", type: "PROVIDER_DELHIVERY" },
    actionType: "SHIPMENT_UPDATED",
    entityType: "SHIPMENT",
    entityId: "AWB-DL928374619",
    description: "Shipment AWB-DL928374619 marked as DELIVERED to Hyderabad residence.",
    whyExplanation: "Courier successfully handed over medication package to Jubilee Hills residence security.",
    metadata: { courier: "Delhivery", recipient: "Security Desk / Ramesh Rao" },
  },
  {
    id: "act-05",
    timestamp: "2026-09-17T11:05:00Z",
    actor: { id: "prov-pinelabs", name: "Pine Labs Gateway", type: "PROVIDER_PINELABS" },
    actionType: "PAYMENT_AUTHORIZED",
    entityType: "AUTHORIZATION",
    entityId: "AUTH-PL-88392",
    description: "Authorized payment of ₹410 for Atorvastatin 20mg refill at Apollo Pharmacy.",
    whyExplanation: "Authorized by Arjun Rao with two-factor biometric confirmation under ₹1,500 spending threshold.",
  },
];
