import {
  LogisticsProvider,
  AddressValidationRequest,
  AddressValidationResponse,
  ShipmentCreationRequest,
  ShipmentResponse,
  LogisticsLifecycleStatus,
} from "@/types/providers";
import { isSandboxMode, formatProviderId } from "@/services/providerConfig";

export class MockDelhiveryLogisticsProvider implements LogisticsProvider {
  name = "Delhivery Healthcare Express Logistics";
  providerStatus: "SANDBOX_SIMULATED" | "LIVE_CONFIGURED" = isSandboxMode()
    ? "SANDBOX_SIMULATED"
    : "LIVE_CONFIGURED";

  private shipments: Map<string, ShipmentResponse> = new Map();

  async validateAddress(address: AddressValidationRequest): Promise<AddressValidationResponse> {
    await new Promise((resolve) => setTimeout(resolve, 300));

    const isHydOrBlrOrChn = ["500033", "500034", "560038", "600020"].some((p) =>
      address.pincode.startsWith(p.slice(0, 3))
    );

    return {
      isValid: true,
      serviceable: true,
      normalizedAddress: `${address.line1}, ${address.city}, ${address.state} - ${address.pincode}`,
      estimatedTransitDays: isHydOrBlrOrChn ? 1 : 2,
    };
  }

  async createShipment(request: ShipmentCreationRequest): Promise<ShipmentResponse> {
    await new Promise((resolve) => setTimeout(resolve, 500));

    const isSandbox = isSandboxMode();
    const rawAwb = `DL${Math.floor(100000000 + Math.random() * 900000000)}`;
    const awbNumber = formatProviderId("AWB", rawAwb);
    const shipmentId = formatProviderId("SHIP", Math.random().toString(36).substring(2, 8).toUpperCase());

    const now = new Date();
    const estDate = new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString().split("T")[0];
    const destination = `${request.deliveryAddress.line1}, ${request.deliveryAddress.city} - ${request.deliveryAddress.pincode}`;

    const shipmentRecord: ShipmentResponse = {
      shipmentId,
      awbNumber,
      status: "PICKUP_SCHEDULED",
      originHub: request.originHub,
      destinationAddress: destination,
      recipientName: request.recipientName,
      responsibleMemberName: request.responsibleMemberName || "Arjun Rao",
      estimatedDeliveryDate: estDate,
      isSandboxSimulated: isSandbox,
      sandboxNotice: isSandbox
        ? "[SANDBOX / SIMULATED] Simulated cold-chain consignment generated by Delhivery test harness."
        : undefined,
      trackingHistory: [
        {
          status: "ORDER_CREATED",
          location: request.originHub,
          timestamp: new Date(now.getTime() - 2 * 60000).toISOString(),
          description: "Prescription validated and cold-chain parcel packaged at Apollo pharmacy.",
        },
        {
          status: "PICKUP_SCHEDULED",
          location: request.originHub,
          timestamp: now.toISOString(),
          description: "Delhivery Healthcare express courier dispatched for pharmacy pickup.",
        },
      ],
    };

    this.shipments.set(awbNumber, shipmentRecord);
    return shipmentRecord;
  }

  async trackShipment(awbNumber: string): Promise<ShipmentResponse> {
    const shipment = this.shipments.get(awbNumber);
    if (shipment) return shipment;

    const isSandbox = isSandboxMode();
    return {
      shipmentId: formatProviderId("SHIP", "PREV-901"),
      awbNumber,
      status: "IN_TRANSIT",
      originHub: "Apollo Begumpet Hub, Hyderabad",
      destinationAddress: "Plot 42, Road No 12, Jubilee Hills, Hyderabad - 500033",
      recipientName: "Anita Rao",
      responsibleMemberName: "Arjun Rao",
      estimatedDeliveryDate: new Date(Date.now() + 18 * 3600 * 1000).toISOString().split("T")[0],
      isSandboxSimulated: isSandbox,
      trackingHistory: [
        {
          status: "ORDER_CREATED",
          location: "Apollo Begumpet Hub",
          timestamp: "2026-09-23T07:15:00Z",
          description: "Consignment manifest created with temperature logging.",
        },
        {
          status: "PICKUP_SCHEDULED",
          location: "Apollo Begumpet Hub",
          timestamp: "2026-09-23T07:45:00Z",
          description: "Courier pickup confirmed.",
        },
        {
          status: "IN_TRANSIT",
          location: "Hyderabad Central Sorting Facility",
          timestamp: "2026-09-23T08:25:00Z",
          description: "Sorted and dispatched to Jubilee Hills local distribution center.",
        },
      ],
    };
  }

  async advanceShipmentStatus(
    awbNumber: string,
    targetStatus?: LogisticsLifecycleStatus
  ): Promise<ShipmentResponse> {
    const shipment = await this.trackShipment(awbNumber);
    const now = new Date().toISOString();

    const sequence: LogisticsLifecycleStatus[] = [
      "ORDER_CREATED",
      "PICKUP_SCHEDULED",
      "IN_TRANSIT",
      "OUT_FOR_DELIVERY",
      "DELIVERED",
    ];

    let nextStatus: LogisticsLifecycleStatus;
    if (targetStatus) {
      nextStatus = targetStatus;
    } else {
      const currentIndex = sequence.indexOf(shipment.status);
      if (currentIndex >= 0 && currentIndex < sequence.length - 1) {
        nextStatus = sequence[currentIndex + 1];
      } else {
        nextStatus = "DELIVERED";
      }
    }

    const descriptions: Record<LogisticsLifecycleStatus, string> = {
      ORDER_CREATED: "Prescription validated and packaging complete.",
      PICKUP_SCHEDULED: "Courier assigned and en route to Apollo pharmacy hub.",
      IN_TRANSIT: "Consignment scanned at Hyderabad Central Sorting Facility. Cold-chain sensor active (4.2°C).",
      OUT_FOR_DELIVERY: "Package out for delivery with Delhivery rider Suresh K. (OTP verification active).",
      DELIVERED: "Delivered to Anita Rao at Jubilee Hills. Doorstep handover confirmed.",
      FAILED: "Delivery attempt failed: Recipient unavailable at registered Jubilee Hills address.",
      CANCELLED: "Shipment cancelled per family coordinator request.",
      DELAYED: "Transit delayed due to local traffic. Rescheduled for evening delivery.",
    };

    const newStep = {
      status: nextStatus,
      location: nextStatus === "DELIVERED" ? "Jubilee Hills, Hyderabad" : "Hyderabad Transit Hub",
      timestamp: now,
      description: descriptions[nextStatus],
    };

    const updatedShipment: ShipmentResponse = {
      ...shipment,
      status: nextStatus,
      trackingHistory: [...shipment.trackingHistory, newStep],
    };

    this.shipments.set(awbNumber, updatedShipment);
    return updatedShipment;
  }
}

export const delhiveryLogisticsProvider: LogisticsProvider = new MockDelhiveryLogisticsProvider();
